"""added Imaya code

Revision ID: 511b4ab5c1c3
Revises: 8cea644aef8c
Create Date: 2019-03-20 14:47:48.144000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511b4ab5c1c3'
down_revision = '8cea644aef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_detail',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('paidDate', sa.String(length=15), nullable=True),
    sa.Column('company', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_detail')
    op.drop_table('payment')
    # ### end Alembic commands ###
