"""added utilitybill model

Revision ID: 8cea644aef8c
Revises: 2129f31651d3
Create Date: 2019-03-20 00:09:37.765000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cea644aef8c'
down_revision = '2129f31651d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_bill',
    sa.Column('billId', sa.Integer(), nullable=False),
    sa.Column('accountNumber', sa.String(length=40), nullable=True),
    sa.Column('accountHolder', sa.String(length=120), nullable=True),
    sa.Column('billingAddress', sa.String(length=120), nullable=True),
    sa.Column('usage', sa.String(length=20), nullable=True),
    sa.Column('duePayment', sa.String(length=40), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('billId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_bill')
    # ### end Alembic commands ###
